import type { ProjectGraph, GraphNode } from '../../domain/graph';
import { neighbors } from '../../domain/graph';
import type { ApiClient } from '../ApiClient';
import type { StepDetail, ReviewAction, PlanProposal } from '../dto';
import { makeFixture } from './fixtures';

export class MockApiClient implements ApiClient {
  private graph: ProjectGraph = makeFixture();
  private subs = new Set<() => void>();

  private notify() {
    this.subs.forEach((cb) => cb());
  }

  subscribe(cb: () => void) {
    this.subs.add(cb);
    return () => {
      this.subs.delete(cb);
    };
  }

  async getGraph(): Promise<ProjectGraph> {
    return structuredClone(this.graph);
  }

  async getStepDetail(stepId: string): Promise<StepDetail> {
    const node = this.graph.nodes.find((n) => n.id === stepId)!;
    const touched = neighbors(this.graph, stepId, 'out').filter((n) => n.kind === 'code_region');
    return {
      node,
      diff: touched.map((c) => ({ path: c.label, patch: sampleDiff(c.label) })),
      decision: neighbors(this.graph, stepId, 'out').find((n) => n.kind === 'decision')?.label,
      acceptance: [{ text: `${node.label} 동작 확인`, met: true }],
      createdNodeIds: touched.map((c) => c.id),
      createdEdgeIds: this.graph.edges.filter((e) => e.from === stepId).map((e) => e.id),
    };
  }

  async proposePlan(target: { goal: string } | { ticketId: string }): Promise<PlanProposal> {
    if ('ticketId' in target) {
      const ticket = this.graph.nodes.find((n) => n.id === target.ticketId);
      const existing = neighbors(this.graph, target.ticketId, 'out')
        .filter((n) => n.kind === 'step')
        .map((s) => ({ label: s.label, intent: '', acceptance: '' }));
      return {
        ticketId: target.ticketId,
        title: ticket?.label,
        steps: existing.length
          ? existing
          : [
              { label: '스펙·골격', intent: '스펙 정리', acceptance: '스펙 합의' },
              { label: '구현', intent: '핵심 구현', acceptance: '동작' },
              { label: '테스트', intent: '테스트 추가', acceptance: '그린' },
            ],
      };
    }
    const goal = target.goal;
    return {
      ticketId: 't-new',
      title: goal,
      steps: [
        { label: '스펙·골격', intent: `${goal} 스펙 정리`, acceptance: '스펙 합의' },
        { label: '구현', intent: '핵심 구현', acceptance: '동작' },
        { label: '테스트', intent: '테스트 추가', acceptance: '그린' },
      ],
    };
  }

  async approvePlan(_p: PlanProposal): Promise<void> {
    this.notify();
  }

  async reviewStep(stepId: string, action: ReviewAction): Promise<void> {
    const node = this.graph.nodes.find((n) => n.id === stepId);
    if (!node) return;
    if (action.kind === 'approve') node.status = 'done';
    else if (action.kind === 'changes') node.status = 'executing';
    else node.status = 'awaiting_review';
    this.notify();
  }

  async owningPath(nodeId: string): Promise<string[]> {
    const order: GraphNode['kind'][] = ['code_region', 'step', 'ticket', 'objective'];
    const path = [nodeId];
    let cur = nodeId;
    for (let i = 0; i < order.length - 1; i++) {
      const parent = neighbors(this.graph, cur, 'in').find((n) => n.kind === order[i + 1]);
      if (!parent) break;
      path.push(parent.id);
      cur = parent.id;
    }
    return path;
  }
}

function sampleDiff(path: string): string {
  return `--- a/${path}\n+++ b/${path}\n@@ -0,0 +1,3 @@\n+// generated by step\n+export const ok = true;\n`;
}
