"""Seed a demo project graph (mirrors the frontend fixture) into the configured
DATABASE_URL, building code-region nodes through the real diff-ingest path.

    DATABASE_URL=sqlite+pysqlite:///./dev.db python seed_demo.py
"""

from app.db import SessionLocal, init_db
from app.graph.store import seed_graph
from app.graph.diff_ingest import apply_step_diff

NODES = [
    {
        "id": "obj",
        "kind": "objective",
        "label": "구독 티어 할일앱",
        "data": {
            "short": "구독 할일앱",
            "description": "Free / Pro / Team 구독 티어와 기능 게이팅을 갖춘 할 일 관리 앱",
        },
    },
    {"id": "t-crud", "kind": "ticket", "label": "할일 CRUD", "status": "done", "data": {"tag": "CRUD"}},
    {"id": "t-gate", "kind": "ticket", "label": "구독 티어 + 기능 게이팅", "status": "executing", "data": {"tag": "GATE"}},
    {"id": "s1", "kind": "step", "label": "할일 모델 + 저장", "status": "done"},
    {"id": "s2", "kind": "step", "label": "할일 추가 폼", "status": "done"},
    {"id": "s3", "kind": "step", "label": "티어 플래그 정의", "status": "done"},
    {"id": "s4", "kind": "step", "label": "게이트 컴포넌트", "status": "awaiting_review"},
    {"id": "s5", "kind": "step", "label": "업그레이드 안내 UI", "status": "planning"},
    {"id": "dec", "kind": "decision", "label": "게이팅은 플래그로 (티어 분기 금지)"},
]
EDGES = [
    {"id": "e1", "from": "obj", "to": "t-crud", "kind": "has"},
    {"id": "e2", "from": "obj", "to": "t-gate", "kind": "has"},
    {"id": "e3", "from": "t-crud", "to": "s1", "kind": "has"},
    {"id": "e4", "from": "t-crud", "to": "s2", "kind": "has"},
    {"id": "e5", "from": "t-gate", "to": "s3", "kind": "has"},
    {"id": "e6", "from": "t-gate", "to": "s4", "kind": "has"},
    {"id": "e7", "from": "t-gate", "to": "s5", "kind": "has"},
    {"id": "e8", "from": "s4", "to": "dec", "kind": "decided"},
]
TOUCHES = [
    ("s1", "src/todo/model.ts"),
    ("s2", "src/todo/TodoForm.tsx"),
    ("s3", "src/billing/flags.ts"),
    ("s4", "src/billing/FeatureGate.tsx"),
]


def _diff(path: str) -> str:
    return (
        f"diff --git a/{path} b/{path}\nnew file mode 100644\n--- /dev/null\n"
        f"+++ b/{path}\n@@ -0,0 +1,2 @@\n+// generated by step\n+export const ok = true;\n"
    )


def main() -> None:
    init_db()
    db = SessionLocal()
    seed_graph(db, "p1", NODES, EDGES)
    for i, (step_id, path) in enumerate(TOUCHES):
        apply_step_diff(db, "p1", step_id, f"sha{i}", _diff(path))
    db.close()
    print("seeded project p1")


if __name__ == "__main__":
    main()
